/**
 * FilmArchivePlanner (FAP)
 * REST API for the FAP backend.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Tag } from '../../tags/models/tag';

export interface CreateUpdateContactDto {
  type: Tag | null;
  name: string;
  email?: string;
  phone?: string;
  website?: string;
}
