image: node:14.18

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/caching/index.html#cache-nodejs-dependencies
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - backend-fap/.npm/
    - frontend-fap/.npm/

stages:
  - build
  - test

build_fe:
  stage: build
  before_script:
    - cd ./frontend-fap
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run build

build_be:
  stage: build
  before_script:
    - cd ./backend-fap
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run build

test_be:
  stage: test
  before_script:
    - cd ./backend-fap
    - npm ci --cache .npm --prefer-offline
  script:
    - npm test
