version: '3.8'

services:
  backend:
    # build:
    #   context: ./backend-fap
    #   dockerfile: Dockerfile
    # user: "${SFTP_UID}:${SFTP_GID}"
    image: node:14.18
    depends_on:
      - db
      - redis
      - sftp
    ports:
      - '${BE_PORT}:3000'
    volumes:
      - './backend-fap/:/app'
      # - '${BE_CACHE_DIR}:${BE_CACHE_DIR}'
    working_dir: /app
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y cmake &&
      npm install &&
      npm run ${BE_NPM_RUN}"
    env_file:
      - .env

  frontend:
    image: node:14.18
    ports:
      - '${FE_PORT}:4200'
    volumes:
      - './frontend-fap/:/app'
    working_dir: /app
    command: >
      bash -c "
      npm install &&
      npm run ${FE_NPM_RUN}"
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - '${ADMINER_PORT}:8080'
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env

  redis:
    image: bitnami/redis:latest
    restart: always
    ports:
      - '${REDIS_PORT_NUMBER}:${REDIS_PORT_NUMBER}'
    env_file:
      - .env

  sftp:
    image: atmoz/sftp:alpine
    restart: always
    ports:
      - '${SFTP_PORT}:22'
    command: ${SFTP_USER}:${SFTP_PASSWORD}:${SFTP_UID}::upload

#host
##################################################################
#                                                                #
#                                                                #
#                                                                #
#                                                                #
#                                                                #
#  docker         :5432               :3000             :8080    #
#  ############################################################  #
#  #              :5432               :3000             :8080 #  #
#  #   ################      ##############     ############# #  #
#  #   #   postgres   #      #   nestjs   #     #  adminer  # #  #
#  #   ################      ##############     ############# #  #
#  ############################################################  #
#                                                                #
