version: '3.8'

services:
  backend:
    image: node:14.18
    depends_on:
      - db
    ports:
      - '${BE_PORT}:3000'
    volumes:
      - './backend-fap/:/app'
    working_dir: /app
    command: >
      bash -c "
      npm install &&
      npm run ${BE_NPM_RUN}"
    env_file:
      - .env

  frontend:
    image: node:14.18
    ports:
      - '${FE_PORT}:4200'
    volumes:
      - './frontend-fap/:/app'
    working_dir: /app
    command: >
      bash -c "
      npm install &&
      npm run ${FE_NPM_RUN}"
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - '${ADMINER_PORT}:8080'
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
#host
##################################################################
#                                                                #
#                                                                #
#                                                                #
#                                                                #
#                                                                #
#  docker         :5432               :3000             :8080    #
#  ############################################################  #
#  #              :5432               :3000             :8080 #  #
#  #   ################      ##############     ############# #  #
#  #   #   postgres   #      #   nestjs   #     #  adminer  # #  #
#  #   ################      ##############     ############# #  #
#  ############################################################  #
#                                                                #