/**
 * FilmArchivePlanner (FAP)
 * REST API for the FAP backend.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateUpdateMovieDto {
  originalTitle: string;
  englishTitle: string;
  movieFiles: string;
  previewFile?: string;
  stillFiles: Array<string>;
  subtitleFiles?: Array<string>;
  directors: Array<number>;
  selectionTags?: Array<string>;
  countriesOfProduction?: Array<string>;
  yearOfProduction?: number;
  duration?: number;
  animationTechniques?: Array<string>;
  softwareUsed?: Array<string>;
  keywords?: Array<string>;
  germanSynopsis: string;
  englishSynopsis: string;
  submissionCategories: Array<string>;
  hasDialog?: boolean;
  dialogLanguages?: Array<string>;
  hasSubtitles?: boolean;
  isStudentFilm: boolean;
  filmSchool?: string;
  script?: string;
  animation?: string;
  editing?: string;
  sound?: string;
  music?: string;
  productionCompany?: string;
  referenceNumber?: string;
  contact: string;
}
