export interface Movie {
  id: Number,
  originalTitle:	string,
  englishTitle:	string,
  movieFile:	string,
  previewFile:	string,
  trailerFile:	string,
  stillFiles:	string[],
  subtitleFiles:	string[],
  directors:	string[],
  countriesOfProduction:	string[],
  yearOfProduction:	number,
  duration:	number, //Duration in minutes
  animationTechniques:	string[],
  softwareUsed:	string[],
  keywords:	string[],
  germanSynopsis:	string,
  englishSynopsis:	string,
  submissionCategory:	string,
  hasDialog:	boolean,
  dialogLanguages:	string[],
  hasSubtitles:	boolean,
  isStudentFilm:	boolean,
  filmSchool:	string,
  script:	string,
  animation:	string,
  editing:	string,
  sound:	string,
  music:	string,
  productionCompany:	string,
  contact:	string
  created_at: Date,
  last_updated: Date,
}
